# Generated by Django 5.2.5 on 2025-09-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
