# Generated by Django 5.2.5 on 2025-09-07 04:09

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cartorderitems_invoice_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', editable=False, length=22, max_length=20, prefix='cat', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghi12345678', editable=False, length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='user_directory_path'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=99.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=66.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=4, max_length=10, prefix='sku', unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijk12345', editable=False, length=10, max_length=20, prefix='ven', unique=True),
        ),
    ]
