# Generated by Django 5.2.5 on 2025-09-07 11:09

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_brand_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='cat', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghi12345678', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijk12345', length=10, max_length=20, prefix='ven', unique=True),
        ),
    ]
