# Generated by Django 5.2.5 on 2025-09-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_cid_alter_product_cid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cid',
            new_name='pid',
        ),
    ]
