# Generated by Django 5.2.5 on 2025-09-07 11:25

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_cid_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghi12345678', length=10, max_length=20, prefix='pro', unique=True),
        ),
    ]
