# Generated by Django 5.2.5 on 2025-09-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_models'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartorder',
            table='core_cartorder',
        ),
        migrations.AlterModelTable(
            name='category',
            table='core_category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='core_product',
        ),
        migrations.AlterModelTable(
            name='productimages',
            table='core_productimage',
        ),
        migrations.AlterModelTable(
            name='productreview',
            table='core_productreview',
        ),
    ]
