# Generated by Django 5.2.5 on 2025-09-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
