# Generated by Django 5.2.5 on 2025-09-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cartorder_invoice_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='invoice_no',
        ),
    ]
