# Generated by Django 5.2.5 on 2025-09-10 10:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_cartorderitems_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
