# Generated by Django 5.2.5 on 2025-09-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cartitem_price_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='product_status',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='product_status',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='processing', max_length=30),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='item_status',
            field=models.CharField(default='processing', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='user_directory_path'),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
